language: php
php:
- '5.3'
- '5.4'
- '5.5'
- '5.6'
env:
  global:
  - secure: mZnk+Ub659qODl3u7oGo1wNEwHBk35VXRaXO9mqkeaswfhasb33qVKnBUeGBAY6UIhKlFPRvljTYb/AryA5X7+tgjmRCi9oY5Yr+vQMVw9vc7R+tr5lNEJEZjyGKA3My6LoWI/zUtszkW1j1zTvY7THejBIiVB/HZ7w6FosSh7U=
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- mkdir -p ~/.composer
- cp .travis.composer.json ~/.composer/config.json
- composer self-update
- composer install --prefer-dist --dev
before_script:
- mkdir -p build/logs
- mkdir -p build/phpdoc
script:
- cd tests
- phpunit -d max_execution_time=0 --coverage-text --coverage-clover ../build/logs/clover.xml
- cd ..
after_script:
- php vendor/bin/coveralls --verbose --config
- vendor/bin/phpdoc -d ./src/AssetsBundle -t ./build/phpdoc
- bash ./build/publish_build.sh
