language: php

matrix:
  include:
    - php: '5.3'
    - php: '5.4'
    - php: '5.5'
    - php: '5.6'
      env:
        - EXECUTE_AFTER_SCRIPT=true

addons:
  apt:
    packages:
    - graphviz

env:
  global:
  - secure: mZnk+Ub659qODl3u7oGo1wNEwHBk35VXRaXO9mqkeaswfhasb33qVKnBUeGBAY6UIhKlFPRvljTYb/AryA5X7+tgjmRCi9oY5Yr+vQMVw9vc7R+tr5lNEJEZjyGKA3My6LoWI/zUtszkW1j1zTvY7THejBIiVB/HZ7w6FosSh7U=
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- mkdir -p ~/.composer
- cp .travis.composer.json ~/.composer/config.json
- composer self-update
- composer install --prefer-dist --dev
before_script:
- mkdir -p build/logs
- mkdir -p build/coverage
- mkdir -p build/phpdoc
script:
- cd tests
- phpunit -d max_execution_time=0 --coverage-text --coverage-clover ../build/logs/clover.xml --coverage-html ../build/coverage/
- cd ..
after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then php vendor/bin/coveralls --verbose --config;fi
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then vendor/bin/phpdoc -d "./src" -t "./build/phpdoc" --template="responsive-twig";fi
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then bash <(curl -s https://gist.githubusercontent.com/neilime/769d733c52acdecea8d2548fb3aca3ff/raw/853d54289f5c449ea9af6a4d8ca92e1f9fc80980/travis_ci_php_publish_build.sh);fi
